# Generated by Django 3.2.16 on 2024-12-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=256, verbose_name='Отправка')),
                ('destination', models.CharField(max_length=256, verbose_name='Прибытие')),
                ('text', models.TextField(verbose_name='Описание')),
                ('airline', models.CharField(max_length=256, verbose_name='Авиакомпания')),
                ('price', models.PositiveBigIntegerField(verbose_name='Стоимость билета')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Продолжительность полёта')),
                ('meals_on_board', models.BooleanField(verbose_name='Питание на борту')),
            ],
            options={
                'verbose_name': 'направление',
                'verbose_name_plural': 'Направления',
            },
        ),
    ]
