# Generated by Django 3.2.16 on 2024-12-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='transcribed_destination',
            field=models.CharField(default='Санкт-Петербург', max_length=256, verbose_name='Прибытие (англ.)'),
            preserve_default=False,
        ),
    ]
