# Generated by Django 3.2.16 on 2024-12-25 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_destination_transcribed_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='text',
            new_name='description',
        ),
    ]
