# Generated by Django 3.2.16 on 2024-12-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_text_destination_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Ticket',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'билет', 'verbose_name_plural': 'Билеты'},
        ),
    ]
